splitted stratum and krnlmon ut as independent actions
Signed-off-by: Aravindkumar Mg <aravindkumar.mg@intel.com>

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -19,9 +19,9 @@ permissions: read-all
 
 jobs:
 
-  build_and_test:
+  build_and_stratum_ut_dpdk_target:
     timeout-minutes: 100
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-latest
     steps:
       - name: 'Checkout p4-dpdk repo'
         uses: actions/checkout@v3
@@ -34,7 +34,7 @@ jobs:
         working-directory: ./p4sde/tools/setup
         run: |
               sudo apt update -y
-              sudo apt install python python3-setuptools python3-pip python3-wheel python3-cffi sudo libssl-dev git zip libatomic1 libnl-route-3-dev curl tree libgtest-dev -y
+              sudo apt install python python3-setuptools python3-pip python3-wheel python3-cffi sudo libssl-dev git zip libatomic1 libnl-route-3-dev curl tree -y
               pip3 install distro
               python3 install_dep.py
               cmake --version
@@ -104,6 +104,62 @@ jobs:
              source ./scripts/dpdk/setup_env.sh $IPDK_RECIPE $SDE_INSTALL $DEPEND_INSTALL
              ./make-all.sh --target=dpdk  --prefix=${GITHUB_WORKSPACE}/dpdk-target
 
+  build_and_krnlmon_ut_dpdk_target:
+    timeout-minutes: 60
+    runs-on: ubuntu-latest
+    steps:
+      - name: 'Checkout p4-dpdk repo'
+        uses: actions/checkout@v3
+        with:
+          repository: p4lang/p4-dpdk-target
+          submodules: 'recursive'
+          path: p4sde
+
+      - name: 'Install dependencies'
+        working-directory: ./p4sde/tools/setup
+        run: |
+              sudo apt update -y
+              sudo apt install python python3-setuptools python3-pip python3-wheel python3-cffi sudo libssl-dev git zip libatomic1 libnl-route-3-dev curl tree -y
+              pip3 install distro
+              python3 install_dep.py
+              cmake --version
+              sudo apt-get purge cmake
+              sudo rm -rf /usr/local/bin/cmake || true
+              sudo rm -rf ~/.local/bin/cmake || true
+              # removing cmake 3.25 and reinstalling 3.20, as build is failing with cmake 3.25
+              wget https://cmake.org/files/v3.20/cmake-3.20.2-linux-x86_64.sh -O ${GITHUB_WORKSPACE}/cmake-3.20.2-linux-x86_64.sh
+              chmod a+x ${GITHUB_WORKSPACE}/cmake-3.20.2-linux-x86_64.sh
+              sudo mkdir -p /opt/rh/cmake
+              cd ${GITHUB_WORKSPACE} && sudo sh cmake-3.20.2-linux-x86_64.sh --prefix=/opt/rh/cmake --skip-license
+              sudo ln -s /opt/rh/cmake/bin/cmake /usr/local/bin/cmake
+              cmake --version
+
+      - name: 'Checkout Networking Recipe'
+        uses: actions/checkout@v3
+        with:
+          submodules: 'recursive'
+          path: ipdk.recipe
+
+      - name: 'Compile P4 dpdk target'
+        run: |
+             export SDE=${GITHUB_WORKSPACE}
+             mkdir install deps
+             export SDE_INSTALL=${GITHUB_WORKSPACE}/install
+             cd ${GITHUB_WORKSPACE}/p4sde
+             ./autogen.sh
+             ./configure --prefix=$SDE_INSTALL
+             make -j6
+             make install
+
+      - name: 'Build,Configure and Execute infrap4d dependencies'
+        run: |
+             cmake --version
+             cd ${GITHUB_WORKSPACE}/ipdk.recipe
+             export IPDK_RECIPE=`pwd`
+             cd $IPDK_RECIPE/setup
+             cmake -B build -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/deps
+             cmake --build build -j6
+
       - name: 'Run Krnlmon Unit Tests for DPDK Target'
         run: |
              cd ${GITHUB_WORKSPACE}/ipdk.recipe
@@ -120,9 +176,9 @@ jobs:
 
   py_bandit_test:
      timeout-minutes: 10
-     runs-on: ubuntu-20.04
+     runs-on: ubuntu-latest
      steps:
-       - name: 'checkout Networking Recipe'
+       - name: 'Checkout Networking Recipe'
          uses: actions/checkout@v3
          with:
            path: ipdk.recipe
